### PR TITLE
RPTDM Update

### PR DESCRIPTION
**Pull request by knitzman**

### CODE REVIEW

**Comment by barbeau** [comment]
@knitzman Thanks for putting this in a PR!  When running this via `AutoRun.bat`, though, I'm still getting prompted for a FDOT database login:

image

Is this expected?  I would have thought that if we're writing to a local file instead of ArcSDE we wouldn't need this.

**Comment by barbeau** [comment]
Ah - I see that the AutoRun.bat is just running the `D7_Desktop_App.jar` that's already built.

Did you use Eclipse to build the project with your modifications?  I was trying to get this up and running in an IDE but neither Eclipse or IntelliJ seemed to want to open this project easily.

**Comment by knitzman** [comment]
A coworker of mine actually did the coding.  I am pretty sure that is what she did.  I am going to try and run the project while logged onto DOT’s VPN and see if that solves the issue.  I’ll get back to you.
-Kelly

**Comment by barbeau** [comment]
@knitzman Based on our discussions the other day, I'm going to close this pull request.  It looks like the best path forward for #3 is switching from ArcSDE to GeoTools for exporting the GTFS data.

**Pull request closed without merging**
